apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client
  namespace: icesi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-client
  template:
    metadata:
      labels:
        app: proxy-client
    spec:
      containers:
        - name: proxy-client
          image: nightparker725/proxy-client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8800
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config.icesi-dev.svc.cluster.local:9296"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery.icesi-dev.svc.cluster.local:8761/eureka"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin.icesi-dev.svc.cluster.local:9411"
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  namespace: icesi-dev
spec:
  selector:
    app: proxy-client
  ports:
    - port: 8900
      targetPort: 8900
  type: ClusterIP
