apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: icesi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
        - name: shipping-service
          image: nightparker725/shipping-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8600
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8600
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8600
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 10
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config.icesi-dev.svc.cluster.local:9296"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery.icesi-dev.svc.cluster.local:8761/eureka"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin.icesi-dev.svc.cluster.local:9411"
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: icesi-dev
spec:
  selector:
    app: shipping-service
  ports:
    - port: 8600
      targetPort: 8600
  type: ClusterIP
