server:
  servlet:
    context-path: /order-service

spring:
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/}
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:9296}
  application:
    name: ORDER-SERVICE
  profiles:
    active:
      - dev

resilience4j:
  bulkhead:
    instances:
      orderDbBulkhead:
        max-concurrent-calls: 10
        max-wait-duration: 0
  circuitbreaker:
    instances:
      orderDb:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        sliding-window-type: COUNT_BASED

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
