server:
  servlet:
    context-path: /product-service

spring:
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/}
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:9296}
  application:
    name: PRODUCT-SERVICE
  profiles:
    active:
      - dev

resilience4j:
  bulkhead:
    instances:
      productReadBulkhead:
        max-concurrent-calls: 10
        max-wait-duration: 0
  circuitbreaker:
    instances:
      productDb:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        sliding-window-type: COUNT_BASED

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      probes:
        enabled: true         # habilita /health/liveness y /health/readiness
      show-details: "always"
  metrics:
    tags:
      application: ${spring.application.name}