name: Deploy to AKS - Prod

on:
  workflow_dispatch:

env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  deploy-to-aks-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Ensure namespace exists
        run: |
          kubectl get namespace icesi-prod || kubectl create namespace icesi-prod

      - name: Deploy manifests to AKS (prod)
        run: |
          kubectl apply -n icesi-prod -f k8s-prod

      - name: Restart deployments (prod)
        run: |
          kubectl rollout restart deployment api-gateway -n icesi-prod
          kubectl rollout restart deployment cloud-config -n icesi-prod
          kubectl rollout restart deployment service-discovery -n icesi-prod
          kubectl rollout restart deployment user-service -n icesi-prod
          kubectl rollout restart deployment product-service -n icesi-prod
          kubectl rollout restart deployment order-service -n icesi-prod
          kubectl rollout restart deployment payment-service -n icesi-prod
          kubectl rollout restart deployment shipping-service -n icesi-prod
          kubectl rollout restart deployment favourite-service -n icesi-prod
          kubectl rollout restart deployment proxy-client -n icesi-prod

      - name: Notify Slack on failure (deploy prod)
        if: failure()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": ":x: *Deploy a AKS (prod) fall√≥* en `${{ github.repository }}`.\nWorkflow: `${{ github.workflow }}`\nBranch: `${{ github.ref_name }}`\nAutor: `${{ github.actor }}`"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
